### ISSUE TITLE
Crash, possibly also related invalid session id.

### ISSUE THREAD

**Issue by Janmm14** [geNAZt/test-website#2]
Error log is much longer, seems to be a thread dump.
`panic: interface conversion: interface is nil, not map[int32]bool
goroutine 1678030 [running]:                                                 runtime.panic(0x9945e0, 0xc208943900)                                                /usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5                        webseite/models/json.(*JSONResponse).BroadcastToServerID(0xc208666ec0, 0xc20$        /go/src/webseite/models/json/jsonResponse.go:31 +0x2ac               webseite/models/json.(*Server).RecalcUptime(0xc2084d1cd0)
        /go/src/webseite/models/json/server.go:375 +0x9c5                    webseite/models/json.ReloadServers(0xc2086a2000, 0x28, 0x40)
        /go/src/webseite/models/json/server.go:203 +0xae7                    webseite/tasks.func  002(0x0, 0x0)
        /go/src/webseite/tasks/mcping.go:81 +0x369                             GNU nano 2.2.6         File: ../../log-mct-003.txt                         [ORM] - 2016-01-23 12:31:10 - [Queries/default] - [  OK /    db.Query /    6$[ORM] - 2016-01-23 12:31:10 - [Queries/default] - [  OK /    db.Query /   13$[ORM] - 2016-01-23 12:31:11 - [Queries/default] - [  OK /    db.Query /   13$serverID: 23                                                                 c: &{0xc2088102d0 0xc20805b200 [0xc208cf31a0] 0xc2086b2190 true}               GNU nano 2.2.6         File: ../../log-mct-003.txt                         [ORM] - 2016-01-23 12:31:10 - [Queries/default] - [  OK /    db.Query /    6$[ORM] - 2016-01-23 12:31:10 - [Queries/default] - [  OK /    db.Query /   13$[ORM] - 2016-01-23 12:31:11 - [Queries/default] - [  OK /    db.Query /   13$serverID: 23                                                                 c: &{0xc2088102d0 0xc20805b200 [0xc208cf31a0] 0xc2086b2190 true}             panic: interface conversion: interface is nil, not map[int32]bool            goroutine 1678030 [running]:                                                 runtime.panic(0x9945e0, 0xc208943900)                                                /usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5                        webseite/models/json.(*JSONResponse).BroadcastToServerID(0xc208666ec0, 0xc20$        /go/src/webseite/models/json/jsonResponse.go:31 +0x2ac               webseite/models/json.(*Server).RecalcUptime(0xc2084d1cd0)                            /go/src/webseite/models/json/server.go:375 +0x9c5                    webseite/models/json.ReloadServers(0xc2086a2000, 0x28, 0x40)                         /go/src/webseite/models/json/server.go:203 +0xae7                    webseite/tasks.func  002(0x0, 0x0)                                                   /go/src/webseite/tasks/mcping.go:81 +0x369                           github.com/astaxie/beego/toolbox.(*Task).Run(0xc20814a300, 0x0, 0x0)                 /go/src/github.com/astaxie/beego/toolbox/task.go:143 +0x4a           created by github.com/astaxie/beego/toolbox.run                                      /go/src/github.com/astaxie/beego/toolbox/task.go:420 +0x549          goroutine 16 [chan receive, 21139 minutes]:                                  github.com/astaxie/beego.(*App).Run(0xc208001110)                                    /go/src/github.com/astaxie/beego/app.go:171 +0x2ac`

**Comment by Janmm14** [comment]
Please note you need to look at your line 28 and not line 31 in jsonResponse.

**Comment by geNAZt** [comment]
Do you try to open the WebSocket without visiting the Website first? Like if you want to read the API only or something?

**Comment by Janmm14** [comment]
Actually not. I'm not using the api only, also I think at that time someone else opened the web page as I gave the url to my server's team.

Edit: The problem might be a longer interupption of the connection and then the web page is visited again (assumption based on your question)
Like you open the web page on your phone, putting it into the background some time and it closes connection. Later on the scket is restarted without reloading the website. Can it be that?
