### ISSUE TITLE
Performance issues with queries containing 'ORDER BY online'

### ISSUE THREAD

**Issue by Janmm14** [geNAZt/test-website#3]
These queries take 2 - 4 seconds to complete.

While that time mysql is running at 100% cpu usage.

I suggest caching the "online record" in the database int he server table and increment it if one finds a higher online time.

**Comment by Janmm14** [comment]
While either you or I fix this issue, I've disabled calculation of player records.

**Comment by geNAZt** [comment]
It should be fixed in the current version. Be sure to have a index on the "online" column in the "ping" Table
